Lambda-School-Labs/allay-be

- README.md
- data/dbConfig.js
- helpers/reviews-model.spec.js
- helpers/users-model.spec.js
- knexfile.js
- package.json
- routers/auth-router.spec.js
- routers/companies-router.spec.js
- routers/reviews-router.spec.js
- routers/users-router.spec.js
setup knex for pg local
changes from SQLite3 to PG for development
> Postgres setup sm

- helpers/companies-model.js
- helpers/companies-model.spec.js
> Company test sm

- README.md
- helpers/companies-model.js
- helpers/reviews-model.js
- helpers/users-model.js
- routers/companies-router.js
- update docs to reflect user env
- update companies router and findCompaniesReview()
- update companies model and findCompanyById() to show reviews as well
> Router messages sm

- middleware/index.js
- middleware/index.spec.js
- package-lock.json
Added 20 tests for middleware functions.
> Middleware testing mw

- README.md
- helpers/users-model.js
- package-lock.json
- routers/users-router.js
- routers/users-router.spec.js
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Users router wc

- data/migrations/20200304132341_add_tagline_to_reviews.js
- data/migrations/20200304134144_add_offer_booleans_reviews.js
- helpers/reviews-model.js
- helpers/users-model.js
Adds three new properties to the reviews table: 
tagline - string, 120 character limit, notNullable
offer_accepted - boolean, DefaultTo(false)
offer_received - boolean, DefaultTo(false)
Also updates the user and reviews models to include these three properties in responses.
> Review tagline mw

- .gitignore
- config/secret.js
> Companies csv add mw wc

- .gitignore
- helpers/reviews-model.js
- helpers/users-model.js
Adds company domain/url to the response on GET requests for reviews
> Model fix reviews mw

- .gitignore
- config/secret.js
Adds the secret.js file back to the project.
> fixes login with JWT

- routers/reviews-router.js
Fixed our UpdateReview function to work.
> fixed our updateReview function to work.

- .codeclimate.yml
- .github/workflows/ci.yml
- package-lock.json
- package.json
> set up github actions, github workflow config, and code coverage"

- data/seeds/001-tracks_table.js
- data/seeds/002-work_status_table.js
- data/seeds/003-interview_topics_table.js
- data/seeds/004-interview_types_table.js
- data/seeds/005-offer_status_table.js
- data/seeds/006-states_table.js
- package-lock.json
- package.json
> Seeding data na

- data/seeds/003-interview_topics_table.js
> Seeded Topics

- README.md
- api/server.js
- helpers/companies-model.js
- helpers/company-reviews-model.js
- helpers/interview-reviews-model.js
- helpers/reviews-model.js
- helpers/users-model.js
- notes.md
- routers/companies-router.js
- routers/company-reviews-router.js
- routers/interview-reviews-router.js
- routers/users-router.js
- added company review
- added company review routers and company review models
- updated existing routers and models
- [x ] This change requires a documentation update
> Update review ap

- README.md
- helpers/interview-reviews-model.js
- helpers/users-model.js
- notes.md
- routers/users-router.js
Cleaning up some things, adding to the ReadME, looking into middleware.
> cleaning up plus a few other things

- helpers/reviews-model.js
- routers/reviews-router.js
Fixed the delete router to work properly. also added user_id to the findReviews model, and company_id to findReviewById.
> Delete Router Fix

- api/server.js
- helpers/company-reviews-model.js
- helpers/interview-reviews-model.js
- helpers/reviews-model.js
- helpers/users-model.js
- middleware/index.js
- routers/auth-router.js
- routers/company-reviews-router.js
- routers/interview-reviews-router.js
- routers/reviews-router.js
- routers/users-router.js
Implementing middleware, created new middleware, cleaning up code
> Cleanup middleware na ap

- README.md
- helpers/companies-model.js
> Add company ap na

- README.md
more fixes, all done now (I think)
> some more fixes

- data/seeds/008-admin_user.js
- middleware/index.js
- routers/auth-router.js
- routers/companies-router.js
- routers/users-router.js
add check for admin middleware and apply to necessary routes. Update admin seed to be encrypted password.
> Admin middleware

- routers/auth-router.js
update router.post to send all signup information to users table
all data was not being sent to the table
> update auth-router to send all signup info to backend table

- data/migrations/20200428091407_users_table.js
ran new migration
portfolio not showing up in users table
> update users table with portfolio

- data/migrations/20200428091407_users_table.js
> update profile_image column

- helpers/users-model.js
- routers/auth-router.js
- routers/users-router.js
update portfolio column
portfolio was not showing up in users table
> update portfolio column

- .eslintrc.js
- .prettierrc.js
- README.md
- package-lock.json
- package.json
I added a config file and settings for Eslint and Prettier so the whole team can have the same syntax. Result: cleaner code
Added config files for Eslint && Prettier
> configured eslint && prettier as well as added configuration to docs

- helpers/reviews-model.js
Adds first_name, last_name, and profile_image to reviews models.
> Add some user information to reviews models

- package.json
Ignore untestable files to improve coverage%
> Ignore migrations, seeds, and coverage directories for code coverage

- middleware/index.js
- routers/auth-router.js
- routers/companies-router.js
- routers/reviews-router.js
- routers/users-router.js
Refactors endpoints to be async for improved consistency
> Async refactor
